#include "IntArray.h"
#include <iostream>
#include <stdlib.h>
#include <stdio.h>
using namespace std;

// Item 1 (Not yet fully optimized at the multiplication section of the multiplyByX function yet, but imull will do until we can find it)

int main(int argc, char *argv[]){
    int x = atoi(argv[1]);
    cout << "	.file	\"multiplyBy" << x << ".cpp\"" << endl;
    cout << "	.text" << endl;
    // Interpretation of IntArray's getSize function (the registers used here are important when this function is called by multiplyByX)
    cout << "	.section	.text._ZN8IntArray7getSizeEv,\"axG\",@progbits,_ZN8IntArray7getSizeEv,comdat" << endl;
    cout << "	.align 2" << endl;
    cout << "	.weak	_ZN8IntArray7getSizeEv" << endl;
    cout << "	.type	_ZN8IntArray7getSizeEv, @function" << endl;
    cout << "_ZN8IntArray7getSizeEv:" << endl;
    cout << ".LFB20:" << endl;
    cout << "	.cfi_startproc" << endl;
    cout << "	endbr64" << endl;
    cout << "	pushq	%rbp" << endl;
    cout << "	.cfi_def_cfa_offset 16" << endl;
    cout << "	.cfi_offset 6, -16" << endl;
    cout << "	movq	%rsp, %rbp" << endl;
    cout << "	.cfi_def_cfa_register 6" << endl;
    cout << "	movq	%rdi, -8(%rbp)" << endl;
    cout << "	movq	-8(%rbp), %rax" << endl;
    cout << "	movl	(%rax), %eax" << endl;
    cout << "	popq	%rbp" << endl;
    cout << "	.cfi_def_cfa 7, 8" << endl;
    cout << "	ret" << endl;
    cout << "	.cfi_endproc" << endl;
    cout << ".LFE20:" << endl;
    cout << "	.size	_ZN8IntArray7getSizeEv, .-_ZN8IntArray7getSizeEv" << endl;
    // Interpretation of IntArray's getElement function (the registers used here are important when this function is called by multiplyByX)
    cout << "	.section	.text._ZN8IntArray10getElementEi,\"axG\",@progbits,_ZN8IntArray10getElementEi,comdat" << endl;
    cout << "	.align 2" << endl;
    cout << "	.weak	_ZN8IntArray10getElementEi" << endl;
    cout << "	.type	_ZN8IntArray10getElementEi, @function" << endl;
    cout << "_ZN8IntArray10getElementEi:" << endl;
    cout << ".LFB22:" << endl;
    cout << "	.cfi_startproc" << endl;
    cout << "	endbr64" << endl;
    cout << "	pushq	%rbp" << endl;
    cout << "	.cfi_def_cfa_offset 16" << endl;
    cout << "	.cfi_offset 6, -16" << endl;
    cout << "	movq	%rsp, %rbp" << endl;
    cout << "	.cfi_def_cfa_register 6" << endl;
    cout << "	movq	%rdi, -8(%rbp)" << endl;
    cout << "	movl	%esi, -12(%rbp)" << endl;
    cout << "	movq	-8(%rbp), %rax" << endl;
    cout << "	movq	8(%rax), %rax" << endl;
    cout << "	movl	-12(%rbp), %edx" << endl;
    cout << "	movslq	%edx, %rdx" << endl;
    cout << "	salq	$2, %rdx" << endl;
    cout << "	addq	%rdx, %rax" << endl;
    cout << "	movl	(%rax), %eax" << endl;
    cout << "	popq	%rbp" << endl;
    cout << "	.cfi_def_cfa 7, 8" << endl;
    cout << "	ret" << endl;
    cout << "	.cfi_endproc" << endl;
    cout << ".LFE22:" << endl;
    cout << "	.size	_ZN8IntArray10getElementEi, .-_ZN8IntArray10getElementEi" << endl;
    // Interpretation of IntArray's setElement function (the registers used here are important when this function is called by multiplyByX)
    cout << "	.section	.text._ZN8IntArray10setElementEii,\"axG\",@progbits,_ZN8IntArray10setElementEii,comdat" << endl;
    cout << "	.align 2" << endl;
    cout << "	.weak	_ZN8IntArray10setElementEii" << endl;
    cout << "	.type	_ZN8IntArray10setElementEii, @function" << endl;
    cout << "_ZN8IntArray10setElementEii:" << endl;
    cout << ".LFB23:" << endl;
    cout << "	.cfi_startproc" << endl;
    cout << "	endbr64" << endl;
    cout << "	pushq	%rbp" << endl;
    cout << "	.cfi_def_cfa_offset 16" << endl;
    cout << "	.cfi_offset 6, -16" << endl;
    cout << "	movq	%rsp, %rbp" << endl;
    cout << "	.cfi_def_cfa_register 6" << endl;
    cout << "	movq	%rdi, -8(%rbp)" << endl;
    cout << "	movl	%esi, -12(%rbp)" << endl;
    cout << "	movl	%edx, -16(%rbp)" << endl;
    cout << "	movq	-8(%rbp), %rax" << endl;
    cout << "	movq	8(%rax), %rax" << endl;
    cout << "	movl	-12(%rbp), %edx" << endl;
    cout << "	movslq	%edx, %rdx" << endl;
    cout << "	salq	$2, %rdx" << endl;
    cout << "	addq	%rax, %rdx" << endl;
    cout << "	movl	-16(%rbp), %eax" << endl;
    cout << "	movl	%eax, (%rdx)" << endl;
    cout << "	nop" << endl;
    cout << "	popq	%rbp" << endl;
    cout << "	.cfi_def_cfa 7, 8" << endl;
    cout << "	ret" << endl;
    cout << "	.cfi_endproc" << endl;
    cout << ".LFE23:" << endl;
    cout << "	.size	_ZN8IntArray10setElementEii, .-_ZN8IntArray10setElementEii" << endl;
    cout << "	.text" << endl;
    // Interpretation of multiplyByX function
    cout << "	.globl	_Z11multiplyBy" << x << "P8IntArray" << endl;
    cout << "	.type	_Z11multiplyBy" << x << "P8IntArray, @function" << endl;
    cout << "_Z11multiplyBy" << x << "P8IntArray:" << endl;
    cout << ".LFB24:" << endl;
    cout << "	.cfi_startproc" << endl;
    cout << "	endbr64" << endl;
    cout << "	pushq	%rbp" << endl;
    cout << "	.cfi_def_cfa_offset 16" << endl;
    cout << "	.cfi_offset 6, -16" << endl;
    cout << "	movq	%rsp, %rbp" << endl;
    cout << "	.cfi_def_cfa_register 6" << endl;
    cout << "	pushq	%rbx" << endl;
    cout << "	subq	$40, %rsp" << endl;
    cout << "	.cfi_offset 3, -24" << endl;
    cout << "	movq	%rdi, -40(%rbp)" << endl;
    cout << "	movl	$0, -20(%rbp)" << endl;
    cout << "	jmp	.L7" << endl;
    cout << ".L8:" << endl;
    cout << "	movq	-40(%rbp), %rbx" << endl;
    cout << "	movl	-20(%rbp), %edx" << endl;
    cout << "	movq	-40(%rbp), %rax" << endl;
    cout << "	movl	%edx, %esi" << endl;
    cout << "	movq	%rax, %rdi" << endl;
    cout << "	call	_ZN8IntArray10getElementEi" << endl;
    cout << "	imull	$" << x << ", %eax, %edx" << endl;
    cout << "	movl	-20(%rbp), %eax" << endl;
    cout << "	movl	%eax, %esi" << endl;
    cout << "	movq	%rbx, %rdi" << endl;
    cout << "	call	_ZN8IntArray10setElementEii" << endl;
    cout << "	addl	$1, -20(%rbp)" << endl;
    cout << ".L7:" << endl;
    cout << "	movq	-40(%rbp), %rax" << endl;
    cout << "	movq	%rax, %rdi" << endl;
    cout << "	call	_ZN8IntArray7getSizeEv" << endl;
    cout << "	cmpl	%eax, -20(%rbp)" << endl;
    cout << "	setl	%al" << endl;
    cout << "	testb	%al, %al" << endl;
    cout << "	jne	.L8" << endl;
    cout << "	nop" << endl;
    cout << "	nop" << endl;
    cout << "	movq	-8(%rbp), %rbx" << endl;
    cout << "	leave" << endl;
    cout << "	.cfi_def_cfa 7, 8" << endl;
    cout << "	ret" << endl;
    cout << "	.cfi_endproc" << endl;
    cout << ".LFE24:" << endl;
    cout << "	.size	_Z11multiplyBy" << x << "P8IntArray, .-_Z11multiplyBy" << x << "P8IntArray" << endl;
    cout << "	.ident	\"GCC: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0\"" << endl;
    cout << "	.section	.note.GNU-stack,\"\",@progbits" << endl;
    cout << "	.section	.note.gnu.property,\"a\"" << endl;
    cout << "	.align 8" << endl;
    cout << "	.long	1f - 0f" << endl;
    cout << "	.long	4f - 1f" << endl;
    cout << "	.long	5" << endl;
    cout << "0:" << endl;
    cout << "	.string	\"GNU\"" << endl;
    cout << "1:" << endl;
    cout << "	.align 8" << endl;
    cout << "	.long	0xc0000002" << endl;
    cout << "	.long	3f - 2f" << endl;
    cout << "2:" << endl;
    cout << "	.long	0x3" << endl;
    cout << "3:" << endl;
    cout << "	.align 8" << endl;
    cout << "4:    " << endl;
    return 0;
}